sudo: required
language: rust
rust:
  - nightly

matrix:
  fast_finish: true

before_install:
  - cargo install grcov

script:
  - export CARGO_INCREMENTAL=0
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
  - export RUSTDOCFLAGS="-Cpanic=abort"
  - cargo build
  - QUICKCHECK_TESTS=10000 cargo test

after_success:
  # measure code coverage and upload to coveralls.io
  - ./coveralls.sh

notifications:
  email: false
  slack: imdea-software:fdyPmym7oicfvSQTL5zy21n3
